2021-08-25 17:57:22,471 INFO    MainThread:36017 [internal.py:wandb_internal():89] W&B internal server running at pid: 36017, started at: 2021-08-25 17:57:22.471126
2021-08-25 17:57:22,472 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: check_version
2021-08-25 17:57:22,473 INFO    WriterThread:36017 [datastore.py:open_for_write():77] open: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/run-xh0f4y0c.wandb
2021-08-25 17:57:22,475 DEBUG   SenderThread:36017 [sender.py:send():182] send: header
2021-08-25 17:57:22,475 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: check_version
2021-08-25 17:57:22,710 DEBUG   SenderThread:36017 [sender.py:send():182] send: run
2021-08-25 17:57:22,972 INFO    SenderThread:36017 [dir_watcher.py:__init__():168] watching files in: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files
2021-08-25 17:57:22,973 INFO    SenderThread:36017 [sender.py:_start_run_threads():743] run started: xh0f4y0c with start time 1629903441
2021-08-25 17:57:22,973 DEBUG   SenderThread:36017 [sender.py:send():182] send: summary
2021-08-25 17:57:22,973 INFO    SenderThread:36017 [sender.py:_save_file():873] saving file wandb-summary.json with policy end
2021-08-25 17:57:22,977 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: run_start
2021-08-25 17:57:22,983 DEBUG   HandlerThread:36017 [meta.py:__init__():39] meta init
2021-08-25 17:57:22,983 DEBUG   HandlerThread:36017 [meta.py:__init__():53] meta init done
2021-08-25 17:57:22,986 DEBUG   HandlerThread:36017 [meta.py:probe():210] probe
2021-08-25 17:57:22,992 DEBUG   HandlerThread:36017 [meta.py:_setup_git():200] setup git
2021-08-25 17:57:23,013 DEBUG   HandlerThread:36017 [meta.py:_setup_git():207] setup git done
2021-08-25 17:57:23,014 DEBUG   HandlerThread:36017 [meta.py:_save_pip():57] save pip
2021-08-25 17:57:23,015 DEBUG   HandlerThread:36017 [meta.py:_save_pip():71] save pip done
2021-08-25 17:57:23,015 DEBUG   HandlerThread:36017 [meta.py:_save_conda():78] save conda
2021-08-25 17:57:23,981 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/wandb-summary.json
2021-08-25 17:57:23,981 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/conda-environment.yaml
2021-08-25 17:57:23,982 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/requirements.txt
2021-08-25 17:57:28,990 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/output.log
2021-08-25 17:57:30,655 DEBUG   HandlerThread:36017 [meta.py:_save_conda():86] save conda done
2021-08-25 17:57:30,655 DEBUG   HandlerThread:36017 [meta.py:probe():252] probe done
2021-08-25 17:57:30,716 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:57:30,717 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:57:30,956 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:30,956 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:30,956 DEBUG   SenderThread:36017 [sender.py:send():182] send: files
2021-08-25 17:57:30,956 INFO    SenderThread:36017 [sender.py:_save_file():873] saving file wandb-metadata.json with policy now
2021-08-25 17:57:30,995 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/conda-environment.yaml
2021-08-25 17:57:30,995 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_created():216] file/dir created: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/wandb-metadata.json
2021-08-25 17:57:31,685 INFO    Thread-11 :36017 [upload_job.py:push():137] Uploaded file /var/folders/cc/2zzy1wh90hqd1432yzc33t0w0000gn/T/tmpa0za294lwandb/27093nzc-wandb-metadata.json
2021-08-25 17:57:34,237 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:34,273 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:34,287 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:34,303 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:34,326 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:34,342 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:34,361 DEBUG   SenderThread:36017 [sender.py:send():182] send: config
2021-08-25 17:57:45,966 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:57:45,967 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:57:51,811 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 17:57:54,066 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/config.yaml
2021-08-25 17:58:01,210 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:58:01,211 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:58:16,465 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:58:16,466 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:58:22,655 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 17:58:31,696 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:58:31,696 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:58:46,930 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:58:46,931 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:58:53,568 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 17:59:02,183 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:59:02,183 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:59:17,905 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:59:17,906 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:59:24,420 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 17:59:33,146 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:59:33,146 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:59:48,380 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 17:59:48,383 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 17:59:55,370 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:00:03,691 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:00:03,750 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:00:19,045 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:00:19,046 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:00:26,349 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:00:34,275 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:00:34,281 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:00:49,519 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:00:49,520 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:00:57,438 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:01:04,784 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:01:04,784 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:01:20,032 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:01:20,033 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:01:28,425 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:01:35,282 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:01:35,284 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:01:50,573 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:01:50,574 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:01:59,394 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:02:05,853 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:02:05,854 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:02:21,119 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:02:21,119 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:02:30,315 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:02:36,362 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:02:36,362 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:02:47,630 ERROR   SenderThread:36017 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd6d3fb3e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d3fb3e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d3fb3e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-08-25 18:03:01,366 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:03:19,019 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:03:19,020 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:03:34,406 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:03:34,410 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:03:35,934 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:03:42,223 WARNING FileStreamThread:36017 [file_stream.py:request_with_retry():466] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fd6d3c71b10>>, args: ('https://api.wandb.ai/files/kaanb/gat/xh0f4y0c/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 0, 'content': ['ERROR 2021-08-25T15:03:00.542325 \x1b[34m\x1b[1mwandb\x1b[39m\x1b[22m: Network error resolved after 0:00:24.175781, resuming normal operation.\n']}}, 'dropped': 0}}
2021-08-25 18:03:49,654 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:03:49,655 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:04:04,879 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:04:04,880 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:04:06,913 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:04:20,101 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:04:20,101 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:04:35,336 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:04:35,336 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:04:37,923 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:04:50,556 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:04:50,556 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:05:05,778 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:05:05,778 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:05:09,232 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 18:05:21,270 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:05:21,271 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:05:36,501 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 18:05:36,501 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 18:05:41,270 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 19:18:41,015 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 19:18:42,144 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 19:18:45,645 ERROR   SenderThread:36017 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd6d4b7d690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d4b7d690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d4b7d690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-08-25 19:19:04,017 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 19:34:31,018 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 19:34:31,019 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 19:34:34,652 ERROR   SenderThread:36017 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd6d4b70b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d4b70b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d4b70b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-08-25 19:34:42,035 WARNING FileStreamThread:36017 [file_stream.py:request_with_retry():466] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fd6d3c71b10>>, args: ('https://api.wandb.ai/files/kaanb/gat/xh0f4y0c/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 15, 'content': ['{"system.cpu": 5.37, "system.memory": 65.73, "system.disk": 59.8, "system.proc.memory.availableMB": 5614.73, "system.proc.memory.rssMB": 41.0, "system.proc.memory.percent": 0.25, "system.proc.cpu.threads": 13.0, "system.network.sent": 2644992, "system.network.recv": 7066624, "_wandb": true, "_timestamp": 1629903941, "_runtime": 500}']}}, 'dropped': 0}}
2021-08-25 19:34:51,199 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 19:34:56,612 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 19:34:56,613 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 19:50:27,135 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 19:50:27,137 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 19:50:36,612 WARNING FileStreamThread:36017 [file_stream.py:request_with_retry():466] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fd6d3c71b10>>, args: ('https://api.wandb.ai/files/kaanb/gat/xh0f4y0c/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 17, 'content': ['{"system.cpu": 28.4, "system.memory": 64.63, "system.disk": 59.8, "system.proc.memory.availableMB": 5794.34, "system.proc.memory.rssMB": 41.03, "system.proc.memory.percent": 0.25, "system.proc.cpu.threads": 13.0, "system.network.sent": 3684352, "system.network.recv": 8733696, "_wandb": true, "_timestamp": 1629909291, "_runtime": 5850}']}}, 'dropped': 0}}
2021-08-25 19:50:39,876 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 19:50:44,436 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 19:50:44,436 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 20:15:05,931 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 20:15:05,933 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 20:15:09,784 ERROR   SenderThread:36017 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd6d4b775d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d4b775d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/kaanbursa/opt/anaconda3/envs/torch/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6d4b775d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-08-25 20:15:23,718 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 20:15:38,060 WARNING FileStreamThread:36017 [file_stream.py:request_with_retry():466] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fd6d3c71b10>>, args: ('https://api.wandb.ai/files/kaanb/gat/xh0f4y0c/file_stream',), kwargs: {'json': {'files': {'wandb-events.jsonl': {'offset': 18, 'content': ['{"system.cpu": 27.31, "system.memory": 64.25, "system.disk": 59.85, "system.proc.memory.availableMB": 5856.95, "system.proc.memory.rssMB": 41.22, "system.proc.memory.percent": 0.25, "system.proc.cpu.threads": 13.0, "system.network.sent": 4196352, "system.network.recv": 9456640, "_wandb": true, "_timestamp": 1629910239, "_runtime": 6798}']}}, 'dropped': 0}}
2021-08-25 20:15:38,710 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 20:15:38,711 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 20:15:49,569 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 20:15:54,430 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 20:15:54,431 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 20:16:09,656 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 20:16:09,656 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 20:16:20,284 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 20:16:24,937 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: stop_status
2021-08-25 20:16:24,938 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: stop_status
2021-08-25 20:16:40,066 DEBUG   SenderThread:36017 [sender.py:send():182] send: telemetry
2021-08-25 20:16:40,067 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:40,067 DEBUG   SenderThread:36017 [sender.py:send():182] send: exit
2021-08-25 20:16:40,067 INFO    SenderThread:36017 [sender.py:send_exit():291] handling exit code: 0
2021-08-25 20:16:40,068 INFO    SenderThread:36017 [sender.py:send_exit():293] handling runtime: 8357
2021-08-25 20:16:40,068 INFO    SenderThread:36017 [sender.py:_save_file():873] saving file wandb-summary.json with policy end
2021-08-25 20:16:40,069 INFO    SenderThread:36017 [sender.py:send_exit():303] send defer
2021-08-25 20:16:40,069 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:40,069 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:40,069 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 0
2021-08-25 20:16:40,070 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:40,070 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 0
2021-08-25 20:16:40,070 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 1
2021-08-25 20:16:40,070 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:40,070 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 1
2021-08-25 20:16:40,163 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:40,164 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 1
2021-08-25 20:16:40,164 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 2
2021-08-25 20:16:40,164 DEBUG   SenderThread:36017 [sender.py:send():182] send: stats
2021-08-25 20:16:40,165 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:40,165 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 2
2021-08-25 20:16:40,165 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:40,165 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 2
2021-08-25 20:16:40,165 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 3
2021-08-25 20:16:40,166 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:40,166 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 3
2021-08-25 20:16:40,166 DEBUG   SenderThread:36017 [sender.py:send():182] send: summary
2021-08-25 20:16:40,166 INFO    SenderThread:36017 [sender.py:_save_file():873] saving file wandb-summary.json with policy end
2021-08-25 20:16:40,167 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:40,167 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 3
2021-08-25 20:16:40,167 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 4
2021-08-25 20:16:40,167 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:40,167 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 4
2021-08-25 20:16:40,168 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:40,168 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 4
2021-08-25 20:16:40,173 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:40,262 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/wandb-summary.json
2021-08-25 20:16:40,263 INFO    Thread-8  :36017 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/output.log
2021-08-25 20:16:43,890 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 5
2021-08-25 20:16:43,890 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:43,891 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:43,891 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 5
2021-08-25 20:16:43,891 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:43,891 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 5
2021-08-25 20:16:43,891 INFO    SenderThread:36017 [dir_watcher.py:finish():282] shutting down directory watcher
2021-08-25 20:16:43,994 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:44,272 INFO    SenderThread:36017 [dir_watcher.py:_on_file_modified():229] file/dir modified: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/config.yaml
2021-08-25 20:16:44,273 INFO    SenderThread:36017 [dir_watcher.py:finish():312] scan: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files
2021-08-25 20:16:44,274 INFO    SenderThread:36017 [dir_watcher.py:finish():318] scan save: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/requirements.txt requirements.txt
2021-08-25 20:16:44,274 INFO    SenderThread:36017 [dir_watcher.py:finish():318] scan save: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/output.log output.log
2021-08-25 20:16:44,275 INFO    SenderThread:36017 [dir_watcher.py:finish():318] scan save: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/config.yaml config.yaml
2021-08-25 20:16:44,282 INFO    SenderThread:36017 [dir_watcher.py:finish():318] scan save: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/wandb-summary.json wandb-summary.json
2021-08-25 20:16:44,283 INFO    SenderThread:36017 [dir_watcher.py:finish():318] scan save: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/conda-environment.yaml conda-environment.yaml
2021-08-25 20:16:44,287 INFO    SenderThread:36017 [dir_watcher.py:finish():318] scan save: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/wandb-metadata.json wandb-metadata.json
2021-08-25 20:16:44,289 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 6
2021-08-25 20:16:44,290 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:44,293 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:44,294 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 6
2021-08-25 20:16:44,296 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:44,296 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 6
2021-08-25 20:16:44,296 INFO    SenderThread:36017 [file_pusher.py:finish():177] shutting down file pusher
2021-08-25 20:16:44,402 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:44,402 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:44,504 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:44,504 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:44,608 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:44,608 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:44,713 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:44,713 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:44,816 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:44,816 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:44,922 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:44,923 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,024 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,024 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,129 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,130 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,236 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,236 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,342 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,343 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,446 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,446 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,551 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,551 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,655 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,656 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,758 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,758 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,862 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,862 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:45,966 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:45,966 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,072 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,072 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,178 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,178 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,280 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,280 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,386 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,386 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,493 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,493 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,599 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,599 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,705 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,705 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,810 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,811 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:46,915 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:46,916 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,018 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,019 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,124 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,124 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,230 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,230 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,336 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,336 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,441 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,441 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,546 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,547 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,651 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,651 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,757 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,758 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,871 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,872 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:47,975 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:47,976 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,081 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:48,081 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,184 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:48,185 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,218 INFO    Thread-16 :36017 [upload_job.py:push():137] Uploaded file /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/conda-environment.yaml
2021-08-25 20:16:48,246 INFO    Thread-15 :36017 [upload_job.py:push():137] Uploaded file /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/wandb-summary.json
2021-08-25 20:16:48,254 INFO    Thread-14 :36017 [upload_job.py:push():137] Uploaded file /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/config.yaml
2021-08-25 20:16:48,268 INFO    Thread-12 :36017 [upload_job.py:push():137] Uploaded file /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/requirements.txt
2021-08-25 20:16:48,289 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:48,289 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,312 INFO    Thread-13 :36017 [upload_job.py:push():137] Uploaded file /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/files/output.log
2021-08-25 20:16:48,395 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:48,395 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,500 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:48,500 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,516 INFO    Thread-7  :36017 [sender.py:transition_state():316] send defer: 7
2021-08-25 20:16:48,516 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:48,516 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 7
2021-08-25 20:16:48,517 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:48,517 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 7
2021-08-25 20:16:48,602 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:48,890 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 8
2021-08-25 20:16:48,890 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,891 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:48,891 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 8
2021-08-25 20:16:48,891 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:48,891 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 8
2021-08-25 20:16:48,891 INFO    SenderThread:36017 [sender.py:transition_state():316] send defer: 9
2021-08-25 20:16:48,892 DEBUG   SenderThread:36017 [sender.py:send():182] send: final
2021-08-25 20:16:48,892 DEBUG   SenderThread:36017 [sender.py:send():182] send: footer
2021-08-25 20:16:48,892 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: defer
2021-08-25 20:16:48,892 INFO    HandlerThread:36017 [handler.py:handle_request_defer():145] handle defer: 9
2021-08-25 20:16:48,893 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: defer
2021-08-25 20:16:48,893 INFO    SenderThread:36017 [sender.py:send_request_defer():312] handle sender defer: 9
2021-08-25 20:16:48,996 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-25 20:16:48,996 DEBUG   SenderThread:36017 [sender.py:send_request():196] send_request: poll_exit
2021-08-25 20:16:48,996 INFO    SenderThread:36017 [file_pusher.py:join():182] waiting for file pusher
2021-08-25 20:16:48,997 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: get_summary
2021-08-25 20:16:48,998 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: sampled_history
2021-08-25 20:16:48,999 DEBUG   HandlerThread:36017 [handler.py:handle_request():128] handle_request: shutdown
2021-08-25 20:16:48,999 INFO    HandlerThread:36017 [handler.py:finish():677] shutting down handler
2021-08-25 20:16:49,896 INFO    WriterThread:36017 [datastore.py:close():281] close: /Users/kaanbursa/Desktop/AI/Torch/Graph/logs/gat/be101a2405b411ecb4adc4b301c9cf33/wandb/run-20210825_175718-xh0f4y0c/run-xh0f4y0c.wandb
2021-08-25 20:16:50,001 INFO    SenderThread:36017 [sender.py:finish():979] shutting down sender
2021-08-25 20:16:50,001 INFO    SenderThread:36017 [file_pusher.py:finish():177] shutting down file pusher
2021-08-25 20:16:50,002 INFO    SenderThread:36017 [file_pusher.py:join():182] waiting for file pusher
2021-08-25 20:16:50,004 INFO    MainThread:36017 [internal.py:handle_exit():76] Internal process exited
